builders:
  nuvigator:
    import: "package:nuvigator/builder.dart"
    builder_factories: ["nuvigatorBuilder"]
    build_extensions: {".dart": [".nuvigator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
targets:
  $default:
    builders:
      nuvigator:
        generate_for:
          - example/**
          - test/**
